name: Build and Deploy GH Pages

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        
      - uses: helaili/jekyll-action@2.0.2
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
